name: "Nanomaps"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate_maps:
    name: "Generate NanoMaps"
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - run: echo "GH_TOKEN=${{ steps.create_token.outputs.token }}" >> "$GITHUB_ENV"

      - name: "Update Branch"
        uses: actions/checkout@v4
        with:
          token: ${{ steps.create_token.outputs.token }}

      - name: Branch
        run: |
          git branch -f nanomap-render
          git checkout nanomap-render
          git reset --hard origin/master

      - name: "Generate Maps"
        run: "./tools/nanomap_renderer/nanomap-renderer-invoker.sh"

      - name: "Commit Maps and open PR"
        run: |
          git config --local user.name "1984-ci-event[bot]"
          git config --local user.email "1283078+1984-ci-event[bot]@users.noreply.github.com"
          git pull origin master
          git add icons/_nanomaps
          git commit -m "NanoMap Update" -a || true
          git push -f -u origin nanomap-render
          result=$(gh pr create -t "Automatic NanoMap Update" -b "Review the diff images before merging." -l "NanoMaps" -H "nanomap-render" -B "master") || true
          if echo "$result" | grep -q "No commits between master and nanomap-render"; then
            echo "No NanoMaps update required, skipping."
            exit 78
          fi
